version: '3.8'
services:
  # API Gateway
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/api-gateway
    networks:
      - app-network

  # Event Bus
  event-bus:
    container_name: event-bus
    build:
      context: .
      dockerfile: ./event-bus/Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - ./event-bus:/event-bus
    networks:
      - app-network

  # Query
  query:
    container_name: query
    build:
      context: .
      dockerfile: ./query/Dockerfile
    ports:
      - "4002:4002"
    volumes:
      - ./query:/query
    depends_on:
      - event-bus
    networks:
      - app-network

  # Volunteers
  volunteer:
    container_name: volunteer
    build:
      context: .
      dockerfile: ./volunteer/Dockerfile
    ports:
      - "4003:4003"
    volumes:
      - ./volunteer:/volunteer
    depends_on:
      - event-bus
    networks:
      - app-network

  # Photo
  photo:
    container_name: photo
    build:
      context: .
      dockerfile: ./photo/Dockerfile
    ports:
      - "4004:4004"
    volumes:
      - ./photo:/photo
    depends_on:
      - event-bus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge